import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/renderer/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#030612',
        'on-primary': '#ffffff',
        'primary-container': '#1a1f2c',
        'on-primary-container': '#828697',
        'inverse-primary': '#c2c6d8',
        'primary-fixed': '#dee2f4',
        'primary-fixed-dim': '#c2c6d8',
        'on-primary-fixed': '#161b28',
        'on-primary-fixed-variant': '#424655',
        'secondary': '#7d562d',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffca98',
        'on-secondary-container': '#7a532a',
        'secondary-fixed': '#ffdcbd',
        'secondary-fixed-dim': '#f0bd8b',
        'on-secondary-fixed': '#2c1600',
        'on-secondary-fixed-variant': '#623f18',
        'tertiary': '#030611',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1a1f2b',
        'on-tertiary-container': '#828795',
        'tertiary-fixed': '#dee2f2',
        'tertiary-fixed-dim': '#c2c6d6',
        'on-tertiary-fixed': '#161c27',
        'on-tertiary-fixed-variant': '#424753',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#faf9f7',
        'on-background': '#1a1c1b',
        'surface': '#faf9f7',
        'surface-dim': '#dadad8',
        'surface-bright': '#faf9f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeec',
        'surface-container-high': '#e9e8e6',
        'surface-container-highest': '#e3e2e0',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#45464c',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1ef',
        'outline': '#76777c',
        'outline-variant': '#c6c6cc',
        'surface-tint': '#595e6d',
        'surface-variant': '#e3e2e0',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'unit': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'gutter': '32px',
        'margin-edge': '64px',
        'section-gap': '128px',
      },
      fontFamily: {
        'h1': ['Newsreader', 'serif'],
        'h2': ['Newsreader', 'serif'],
        'h3': ['Newsreader', 'serif'],
        'body-lg': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Space Grotesk', 'sans-serif'],
        'ui-label': ['Space Grotesk', 'sans-serif'],
        'caption': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'h1': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'h2': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'h3': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'ui-label': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config
